### ISSUE TITLE
Initial data acquisition for trial data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/scraper#4]
# Description

Seed the data warehouse with core trial data from clinical trial registers.

## Registers

We maintain a list of [clinical trial registers here](https://github.com/opentrials/registers). The following are relevant for initial data acquisition.

* [x] ClinicalTrials.gov
* [x] ISRCTN
* [x] EU-CTR
* [x] JPRN
* [x] ANZCTR
* [x] GSK
* [x] Pfizer
* [x] Takeda
* [x] WHO ICTRP

# Tasks

For each register:

* [x] Record audit: `created` (timestamp), `modified` (timestamp), `source` (url)
* [x] auto-generated identifier (uuid4) for OpenTrials databases (consistent over time, consistent across Warehouse, Datastore and Database)
* [x] Data update strategy: (frequency, modified records, new records)
* [x] README.md: scraper overview
* [x] README.md: source data model
* [x] README.md: warehouse data model
* [x] README.md: description of primary identifiers in *source* (if more than one)
* [x] README.md: Link to license terms for the source data
* [x] Table in the Data Warehouse for acquired data
* [x] Initial bulk data acquisition

**Comment by roll** [comment]
DONE
